[package]
name = "cge"
version = "0.1.0"
authors = [
    "pengowen123 <pengowen816@gmail.com>",
    "MathisWellmann <wellmannmathis@gmail.com>",
]
edition = "2018"

[dependencies]
log = "0.4.11"
pretty_env_logger = "0.4.0"